In [2]:
import pandas as pd

workers = {
    
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan", "Anjali", "Vikram", "Meera"],
    "Age": [25, 30, 28, 35, 40, 27, 32, 29],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing", "HR", "Finance", "IT"],
    "Salary": [35000, 60000, 50000, 75000, 65000, 40000, 55000, 62000],
    "Experience": [2, 5, 4, 8, 10, 3, 6, 5],
    "City": ["Chennai", "Bangalore", "Hyderabad", "Chennai", "Mumbai", "Pune", "Delhi", "Bangalore"]
}

df = pd.DataFrame(workers)

display(df)

     Name  Age Department  Salary  Experience       City
0    Amit   25         HR   35000           2    Chennai
1   Priya   30         IT   60000           5  Bangalore
2   Rahul   28    Finance   50000           4  Hyderabad
3   Sneha   35         IT   75000           8    Chennai
4   Karan   40  Marketing   65000          10     Mumbai
5  Anjali   27         HR   40000           3       Pune
6  Vikram   32    Finance   55000           6      Delhi
7   Meera   29         IT   62000           5  Bangalore

In [3]:
# adding column
df["Bonus"] = df['Salary']*0.1 + 1000
display(df)

     Name  Age Department  Salary  Experience       City   Bonus
0    Amit   25         HR   35000           2    Chennai  4500.0
1   Priya   30         IT   60000           5  Bangalore  7000.0
2   Rahul   28    Finance   50000           4  Hyderabad  6000.0
3   Sneha   35         IT   75000           8    Chennai  8500.0
4   Karan   40  Marketing   65000          10     Mumbai  7500.0
5  Anjali   27         HR   40000           3       Pune  5000.0
6  Vikram   32    Finance   55000           6      Delhi  6500.0
7   Meera   29         IT   62000           5  Bangalore  7200.0

In [4]:
#insert() => df.insert(position,"col_name",some_data)

df.insert(0, "Employee_ID", [101, 102, 103, 104, 105, 106, 107, 108])
display(df)



print(90*"=")

# updating  .loc[row_index,"column_name",updated_value]
df.loc[0, 'Salary'] = 50000
display(df)

   Employee_ID    Name  Age Department  Salary  Experience       City   Bonus
0          101    Amit   25         HR   35000           2    Chennai  4500.0
1          102   Priya   30         IT   60000           5  Bangalore  7000.0
2          103   Rahul   28    Finance   50000           4  Hyderabad  6000.0
3          104   Sneha   35         IT   75000           8    Chennai  8500.0
4          105   Karan   40  Marketing   65000          10     Mumbai  7500.0
5          106  Anjali   27         HR   40000           3       Pune  5000.0
6          107  Vikram   32    Finance   55000           6      Delhi  6500.0
7          108   Meera   29         IT   62000           5  Bangalore  7200.0

==========================================================================================

   Employee_ID    Name  Age Department  Salary  Experience       City   Bonus
0          101    Amit   25         HR   50000           2    Chennai  4500.0
1          102   Priya   30         IT   60000           5  Bangalore  7000.0
2          103   Rahul   28    Finance   50000           4  Hyderabad  6000.0
3          104   Sneha   35         IT   75000           8    Chennai  8500.0
4          105   Karan   40  Marketing   65000          10     Mumbai  7500.0
5          106  Anjali   27         HR   40000           3       Pune  5000.0
6          107  Vikram   32    Finance   55000           6      Delhi  6500.0
7          108   Meera   29         IT   62000           5  Bangalore  7200.0

In [5]:
# remove columns
# df.drop(columns = ['columnName'],inplace=True)


df.drop(columns=['Experience'],inplace=True)
display(df)


# for drop mul columns => df.drop(columns=['Experience','Age'],inplace=True)

   Employee_ID    Name  Age Department  Salary       City   Bonus
0          101    Amit   25         HR   50000    Chennai  4500.0
1          102   Priya   30         IT   60000  Bangalore  7000.0
2          103   Rahul   28    Finance   50000  Hyderabad  6000.0
3          104   Sneha   35         IT   75000    Chennai  8500.0
4          105   Karan   40  Marketing   65000     Mumbai  7500.0
5          106  Anjali   27         HR   40000       Pune  5000.0
6          107  Vikram   32    Finance   55000      Delhi  6500.0
7          108   Meera   29         IT   62000  Bangalore  7200.0

In [6]:
# df= df.drop(1) => Drops row with index 1
df= df.drop(1)
display(df)


# df = df.drop([0, 2]) => drop multiple rows
# df = df.drop('Age', axis=1) => drop by column name
# df = df.drop(['Age', 'Name'], axis=1) => drop multiple columns
# df = df.drop(columns=['Age']) => instead of axis = 1
# df.drop('Age', axis=1, inplace=True) =

   Employee_ID    Name  Age Department  Salary       City   Bonus
0          101    Amit   25         HR   50000    Chennai  4500.0
2          103   Rahul   28    Finance   50000  Hyderabad  6000.0
3          104   Sneha   35         IT   75000    Chennai  8500.0
4          105   Karan   40  Marketing   65000     Mumbai  7500.0
5          106  Anjali   27         HR   40000       Pune  5000.0
6          107  Vikram   32    Finance   55000      Delhi  6500.0
7          108   Meera   29         IT   62000  Bangalore  7200.0

In [7]:
# Handling missing data
# NaN(Not a number), None(for object data types)
# isnull() ,True -> NaN is missing

import pandas as pd

workers_Info = {
    
    "Name": ["Amit", 'shyam', "Rahul", "Sneha", "Karan", "Anjali", "Vikram", "Meera"],
    "Age": [25, 30, 28, 35, 40, None, 32, 29],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing", "HR", "Finance", "IT"],
    "Salary": [35000, None, 50000, 75000, 65000, 40000, 55000, 62000],
    "Experience": [2, 5, 4, 8, 10, 3, 6, 5],
    "City": ["Chennai", "Bangalore", "Hyderabad", "Chennai", "Mumbai", "Pune", "Delhi", "Bangalore"]
}

df = pd.DataFrame(workers_Info)
display(df.isnull())

print(25 * "=", "total of missing values", 25 * "=")

display(df.isnull().sum())

    Name    Age  Department  Salary  Experience   City
0  False  False       False   False       False  False
1  False  False       False    True       False  False
2  False  False       False   False       False  False
3  False  False       False   False       False  False
4  False  False       False   False       False  False
5  False   True       False   False       False  False
6  False  False       False   False       False  False
7  False  False       False   False       False  False

========================= total of missing values =========================

Name          0
Age           1
Department    0
Salary        1
Experience    0
City          0
dtype: int64

In [8]:
# filling default values in the missing places => data cleaning

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Age'] = df['Age'].astype(int)


df['Salary'] = df['Salary'].fillna(df['Salary'].mean()).astype(int)
display(df)

     Name  Age Department  Salary  Experience       City
0    Amit   25         HR   35000           2    Chennai
1   shyam   30         IT   54571           5  Bangalore
2   Rahul   28    Finance   50000           4  Hyderabad
3   Sneha   35         IT   75000           8    Chennai
4   Karan   40  Marketing   65000          10     Mumbai
5  Anjali   31         HR   40000           3       Pune
6  Vikram   32    Finance   55000           6      Delhi
7   Meera   29         IT   62000           5  Bangalore

In [9]:
# interpolation => fill estimated value  => for numerical values
# linear,polynomial, time
# while working with time series data
# numeric data with trend
# avoid dropping rows
# dis => it won't work with categorical data

import pandas as pd

df = pd.DataFrame({
    "Sales": [100, None, 300]
})


df["Sales"] = df["Sales"].interpolate()
print(df)

   Sales
0  100.0
1  200.0
2  300.0

### sorting & aggregation

In [10]:
# sorting data
# df.sort_values(by="column name",true, inplace=True) => true for ascending

import pandas as pd

employees = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Amit", "Rahul", "Sneha", "Karan", "Anjali",
             "Vikram", "Meera", "Priya", "Arjun", "Neha"],
    "Age": [25, 30, 30, None, 40, 32, 29, 25, None, 31],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing",
                   "HR", "Finance", "IT", "Sales", "Marketing"],
    "Salary": [35000, 60000, 50000, 75000, None,
               40000, 55000, 62000, 48000, 70000],
    "Experience": [2, 5, 4, 8, 10, 3, 6, 5, 4, 7],
    "City": ["Chennai", "Bangalore", "Hyderabad", "Chennai", "Mumbai",
             "Pune", "Delhi", "Bangalore", "Chennai", "Mumbai"]
}

df = pd.DataFrame(employees)

df.sort_values(by='Age',ascending=True,inplace=True)
display(df)

   Employee_ID    Name   Age Department   Salary  Experience       City
0          101    Amit  25.0         HR  35000.0           2    Chennai
7          108   Priya  25.0         IT  62000.0           5  Bangalore
6          107   Meera  29.0    Finance  55000.0           6      Delhi
1          102   Rahul  30.0         IT  60000.0           5  Bangalore
2          103   Sneha  30.0    Finance  50000.0           4  Hyderabad
9          110    Neha  31.0  Marketing  70000.0           7     Mumbai
5          106  Vikram  32.0         HR  40000.0           3       Pune
4          105  Anjali  40.0  Marketing      NaN          10     Mumbai
3          104   Karan   NaN         IT  75000.0           8    Chennai
8          109   Arjun   NaN      Sales  48000.0           4    Chennai

In [11]:
# multiple condition sorting

df.sort_values(by=['Age','Salary'],ascending=[True,False],inplace=True)
print('sorted by age ascending  and salary by descending ')
display(df)

sorted by age ascending  and salary by descending

   Employee_ID    Name   Age Department   Salary  Experience       City
7          108   Priya  25.0         IT  62000.0           5  Bangalore
0          101    Amit  25.0         HR  35000.0           2    Chennai
6          107   Meera  29.0    Finance  55000.0           6      Delhi
1          102   Rahul  30.0         IT  60000.0           5  Bangalore
2          103   Sneha  30.0    Finance  50000.0           4  Hyderabad
9          110    Neha  31.0  Marketing  70000.0           7     Mumbai
5          106  Vikram  32.0         HR  40000.0           3       Pune
4          105  Anjali  40.0  Marketing      NaN          10     Mumbai
3          104   Karan   NaN         IT  75000.0           8    Chennai
8          109   Arjun   NaN      Sales  48000.0           4    Chennai

In [12]:
# summary statistics
# df['Column Name'].mean(),df['Column Name'].max(),df['Column Name'].min()

avg_sal = df['Salary'].mean()
print(avg_sal)

55000.0

In [13]:
# grouping
grouped = df.groupby('Age')['Salary'].sum()
print(grouped)

# for multiple columns
# grouped = df.groupby(['Age','Name'])['Salary'].sum

Age
25.0     97000.0
29.0     55000.0
30.0    110000.0
31.0     70000.0
32.0     40000.0
40.0         0.0
Name: Salary, dtype: float64

In [14]:
# aggregation => sum(),mean(),count(),min(),max()
# merging & concatenating => pd.merge(df1,df2,on='column name', how='type of join')

import pandas as pd
df_customer = pd.DataFrame({
  'CusID':[1,2,3],
  'Name':['Sam','Ram','Shyam']
})

df_orders = pd.DataFrame({
  'CusID':[1,2,4],
  'OrderAmount':[240,450,350]
})


# merger
df_merged = pd.merge(df_customer,df_orders,on='CusID',how='inner') #outer,left,right,cross
print(df_merged)

   CusID Name  OrderAmount
0      1  Sam          240
1      2  Ram          450